In [2]:
import numpy as np




In [3]:
### creating array from list
arr_1 = np.array([1,2,3,4,5])
arr_1

arr_2 = np.array([[1,2,3],[4,5,6]])
arr_2



array([[1, 2, 3],
       [4, 5, 6]])

### List vs numpy array

In [4]:
py_list = [1,2,3]
print(py_list * 2)

np_array = np.array([1,2,3])
print(np_array * 2)



import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n list operation time: ",time.time() - start)


start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ",time.time() - start)






[1, 2, 3, 1, 2, 3]
[2 4 6]

 list operation time:  0.09835004806518555

 Numpy operation time:  0.005417823791503906


# creating array from scratch


In [5]:
zeros = np.zeros((3,4))
print(zeros)

print("\n")

ones = np.ones((3,4))
ones 

full = np.full((2,2),7)
full


random = np.random.random((2,3))
print(random)

print('\n')

sequence = np.arange(1,31,2)
print(sequence)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[0.36866815 0.6424148  0.63352971]
 [0.12690059 0.86741412 0.93148257]]


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


### Vector, Matrix, Tensor


In [6]:
vector = np.array([1,2,3])
print("Vector: ", vector)


matrix = np.array([[1,2,3]
                   ,[4,5,6]])
print("Matrix: ", matrix)


tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [7]:
arr =np.array([[1,2,3],
              [4,5,6]])

print("Shape: ",arr.shape)
print("Dimension",arr.ndim)
print("Size ", arr.size)
print("Dtype ", arr.dtype)


Shape:  (2, 3)
Dimension 2
Size  6
Dtype  int64


###  Array Reshaping

In [8]:
arr =np.arange(12)
print(arr)

#Reshape 

reshaped = arr.reshape((3,4))
print(reshaped)


#to flattened
flattened = reshaped.flatten()
print(flattened)


#Ravel  (returns view , instead of copy)
raveled = reshaped.ravel()
print(raveled)


#Transpose
transpose = reshaped.T
print('\n Transposed array ', transpose)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Phase 2 

In [9]:
# Numpy Array Operations

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("slicing ", arr[2:7])
print("With Step",arr[1:8:2])
print("Neagative indexing ",arr[-3:])

slicing  [3 4 5 6 7]
With Step [2 4 6 8]
Neagative indexing  [ 8  9 10]


In [10]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific element: ",arr_2d[1,2] )
print("Specifuc element: ",arr_2d[2,1])

print("Entire column: ", arr_2d[:,2])



Specific element:  6
Specifuc element:  8
Entire column:  [3 6 9]


## Sorting

In [11]:
arr = np.array([4,3,5,6,4,8,9,2,1,7])
print("Sorted Array: ", np.sort(arr))


## 2d array

arr_2d = np.array([[5,3],[2,4],[9,1]])
print("Sorted 2d array by column", np.sort(arr_2d, axis=0))
print("Sorted 2d array by row", np.sort(arr_2d, axis=1))


Sorted Array:  [1 2 3 4 4 5 6 7 8 9]
Sorted 2d array by column [[2 1]
 [5 3]
 [9 4]]
Sorted 2d array by row [[3 5]
 [2 4]
 [1 9]]


In [12]:
## Filter


numbers = np.arange(1,11)
print(numbers)

even_numbers = numbers[numbers % 2 == 0]
print(even_numbers)



## Filter with Mask

mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
Numbers greater than 5  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [13]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 9)
print(where_result)

print(numbers[where_result])

[1 3 5]
(array([9]),)
[10]


In [15]:
condition_array = np.where(numbers > 3 , "true", 'false')
print(condition_array)

['false' 'false' 'false' 'true' 'true' 'true' 'true' 'true' 'true' 'true']


### Adding and removing data


In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


In [20]:
##array compatibility

a= np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,4])

print("compatibility shapes", a.shape == b.shape)
print("compatibility shapes", a.shape == c.shape)

compatibility shapes True
compatibility shapes False


In [30]:
a = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

add_row = np.vstack((a,new_row))

print(a)

print('\n')

print(new_row)

print('\n')

print(add_both)





print('\n')


#add column

b=np.array([[1,2],[3,4]])

new_colum = np.array([[6],[7]])

add_column = np.hstack((b,new_colum))


print(add_column)

[[1 2]
 [3 4]]


[[5 6]]


[[1 2]
 [3 4]
 [5 6]]


[[1 2 6]
 [3 4 7]]


In [31]:
## deletin

arr=np.array([1,2,3,4])

deleted = np.delete(arr,2)
print(deleted)

[1 2 4]


## Phase 3
